resolver 172.20.0.10 valid=30s;

server {
    listen 80;

    set $s3 "aurya.dataiesb.com.s3-website-us-east-1.amazonaws.com";
    set $backend "aurya-backend-svc.custom.svc.cluster.local";

    location = /_stcore/health {
        return 200 'ok';
    }

    location /questions {
        proxy_pass http://$backend:8000;
    }

    location /tts {
        proxy_pass http://$backend:8000;
    }

    location /ws/ {
        proxy_pass http://$backend:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    location / {
        proxy_pass http://$s3/;
        proxy_set_header Host $s3;
        proxy_intercept_errors on;
    }
}
