apiVersion: apps/v1
kind: Deployment
metadata:
  name: aurya-frontend-v2
  namespace: custom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aurya-frontend-v2
  template:
    metadata:
      labels:
        app: aurya-frontend-v2
    spec:
      containers:
      - name: frontend
        image: 248189947068.dkr.ecr.us-east-1.amazonaws.com/aurya-frontend-v2:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aurya-frontend-v2-svc
  namespace: custom
spec:
  selector:
    app: aurya-frontend-v2
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
